Not Found: /favicon.ico
Internal Server Error: /net/network/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: meetnet/network_detail.html
Internal Server Error: /net/network/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: meetnet/network_detail.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 110, in get
    self.object = self.get_object()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 48, in get_object
    % self.__class__.__name__)
AttributeError: Generic detail view NetworkView must be called with either an object pk or a slug.
Internal Server Error: /net/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: meetnet/network_detail.html
Internal Server Error: /net/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: meetnet/network_detail.html
Internal Server Error: /net/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 101, in render
    compiled_parent = self.get_parent(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 98, in get_parent
    return get_template(parent)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: bootbase.html
Internal Server Error: /
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 110, in get
    self.object = self.get_object()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 48, in get_object
    % self.__class__.__name__)
AttributeError: Generic detail view NetworkView must be called with either an object pk or a slug.
Internal Server Error: /
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 186, in select_template
    raise TemplateDoesNotExist(', '.join(not_found))
TemplateDoesNotExist: home.html
Not Found: /admin/data/projectlocatie/5/
Internal Server Error: /
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 56, in resolve_template
    return loader.select_template(template)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 180, in select_template
    return get_template(template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 127, in find_template
    source, display_name = loader(name, dirs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 43, in __call__
    return self.load_template(template_name, template_dirs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 49, in load_template
    template = get_template_from_string(source, origin, template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 149, in get_template_from_string
    return Template(source, origin, name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 125, in __init__
    self.nodelist = compile_string(template_string, origin)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 153, in compile_string
    return parser.parse()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 215, in do_extends
    nodelist = parser.parse()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 190, in do_block
    nodelist = parser.parse(('endblock',))
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/templatetags/l10n.py", line 60, in localize_tag
    nodelist = parser.parse(('endlocalize',))
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 278, in parse
    compiled_result = compile_func(self, token)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 956, in do_if
    nodelist = parser.parse(('endif',))
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 276, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 331, in invalid_block_tag
    (command, get_text_list(["'%s'" % p for p in parse_until])))
TemplateSyntaxError: Invalid block tag: 'endlocalize', expected 'endif'
Not Found: /media/bound/noorderzijlvest.geojson
Internal Server Error: /admin/meetnet/well/add/
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 465, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1181, in add_view
    for FormSet, inline in zip(self.get_formsets(request), inline_instances):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in get_formsets
    yield inline.get_formset(request, obj)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1700, in get_formset
    return inlineformset_factory(self.parent_model, self.model, **defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 985, in inlineformset_factory
    FormSet = modelformset_factory(model, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 813, in modelformset_factory
    labels=labels, help_texts=help_texts, error_messages=error_messages)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 528, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 282, in __new__
    opts.help_texts, opts.error_messages)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 205, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "/home/theo/acaciadata.com/acacia/acacia/meetnet/admin.py", line 38, in formfield_for_dbfield
    return db_field.formfield(**kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 397, in formfield
    return super(ImageField, self).formfield(**defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 290, in formfield
    return super(FileField, self).formfield(**defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 554, in formfield
    return form_class(**defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/fields.py", line 549, in __init__
    super(FileField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'request'
Internal Server Error: /admin/meetnet/photo/add/
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 465, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1141, in add_view
    ModelForm = self.get_form(request)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 536, in get_form
    fields = flatten_fieldsets(self.get_fieldsets(request, obj))
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 524, in get_fieldsets
    form = self.get_form(request, obj, fields=None)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 561, in get_form
    return modelform_factory(self.model, **defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 528, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 282, in __new__
    opts.help_texts, opts.error_messages)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 205, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "/home/theo/acaciadata.com/acacia/acacia/meetnet/admin.py", line 50, in formfield_for_dbfield
    return db_field.formfield(**kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 397, in formfield
    return super(ImageField, self).formfield(**defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 290, in formfield
    return super(FileField, self).formfield(**defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 554, in formfield
    return form_class(**defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/fields.py", line 549, in __init__
    super(FileField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'request'
Internal Server Error: /admin/meetnet/well/add/
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 465, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func(self, *args2, **kwargs2)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/transaction.py", line 371, in inner
    return func(*args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1181, in add_view
    for FormSet, inline in zip(self.get_formsets(request), inline_instances):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 616, in get_formsets
    yield inline.get_formset(request, obj)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/options.py", line 1700, in get_formset
    return inlineformset_factory(self.parent_model, self.model, **defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 985, in inlineformset_factory
    FormSet = modelformset_factory(model, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 813, in modelformset_factory
    labels=labels, help_texts=help_texts, error_messages=error_messages)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 528, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 282, in __new__
    opts.help_texts, opts.error_messages)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/models.py", line 205, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "/home/theo/acaciadata.com/acacia/acacia/meetnet/admin.py", line 38, in formfield_for_dbfield
    return db_field.formfield(**kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 397, in formfield
    return super(ImageField, self).formfield(**defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 290, in formfield
    return super(FileField, self).formfield(**defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/__init__.py", line 554, in formfield
    return form_class(**defaults)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/forms/fields.py", line 549, in __init__
    super(FileField, self).__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'request'
Internal Server Error: /net/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 111, in get
    context = self.get_context_data(object=self.object)
  File "/home/theo/acaciadata.com/acacia/acacia/meetnet/views.py", line 46, in get_context_data
    'info': render_to_string('well_info.html', {'object': well, 'chart': None if well.chart.name is None else well.chart.url})
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 63, in _get_url
    self._require_file()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 41, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'chart' attribute has no file associated with it.
Internal Server Error: /net/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 111, in get
    context = self.get_context_data(object=self.object)
  File "/home/theo/acaciadata.com/acacia/acacia/meetnet/views.py", line 50, in get_context_data
    'info': render_to_string('well_info.html', {'object': well, 'chart': chart})
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 162, in render_to_string
    t = get_template(template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 138, in get_template
    template, origin = find_template(template_name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader.py", line 131, in find_template
    raise TemplateDoesNotExist(name)
TemplateDoesNotExist: well_info.html
Internal Server Error: /net/well/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/generic/detail.py", line 111, in get
    context = self.get_context_data(object=self.object)
  File "/home/theo/acaciadata.com/acacia/acacia/meetnet/views.py", line 21, in get_context_data
    context['chart'] = None if well.chart.name is None else well.chart.url
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 63, in _get_url
    self._require_file()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 41, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'chart' attribute has no file associated with it.
Not Found: /media/
Not Found: /media/
Internal Server Error: /net/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/templatetags/l10n.py", line 35, in render
    output = self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 88, in render
    output = self.filter_expression.resolve(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 585, in resolve
    obj = self.var.resolve(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 771, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 63, in _get_url
    self._require_file()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 41, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'bound' attribute has no file associated with it.
Internal Server Error: /net/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/templatetags/l10n.py", line 35, in render
    output = self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 88, in render
    output = self.filter_expression.resolve(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 585, in resolve
    obj = self.var.resolve(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 771, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 63, in _get_url
    self._require_file()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 41, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'bound' attribute has no file associated with it.
Internal Server Error: /net/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/templatetags/l10n.py", line 35, in render
    output = self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 88, in render
    output = self.filter_expression.resolve(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 585, in resolve
    obj = self.var.resolve(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 771, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 63, in _get_url
    self._require_file()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 41, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'bound' attribute has no file associated with it.
Internal Server Error: /net/1
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/templatetags/l10n.py", line 35, in render
    output = self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 88, in render
    output = self.filter_expression.resolve(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 585, in resolve
    obj = self.var.resolve(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 735, in resolve
    value = self._resolve_lookup(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 771, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 63, in _get_url
    self._require_file()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/db/models/fields/files.py", line 41, in _require_file
    raise ValueError("The '%s' attribute has no file associated with it." % self.field.name)
ValueError: The 'bound' attribute has no file associated with it.
Not Found: /media/
Not Found: /admin/gorinchem/
Not Found: /media/
Not Found: /media/
Not Found: /media/
Not Found: /media/
Not Found: /media/
Not Found: /media/
Not Found: /media/
Internal Server Error: /admin/meetnet/
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 215, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/decorators.py", line 99, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 198, in inner
    return view(request, *args, **kwargs)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 414, in app_index
    model_dict['admin_url'] = reverse('admin:%s_%s_changelist' % info, current_app=self.name)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 507, in reverse
    app_list = resolver.app_dict[ns]
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 329, in app_dict
    self._populate()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 290, in _populate
    for name in pattern.reverse_dict:
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 315, in reverse_dict
    self._populate()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 303, in _populate
    lookups.appendlist(pattern.callback, (bits, p_pattern, pattern.default_args))
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 230, in callback
    self._callback = get_callable(self._callback_str)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/functional.py", line 32, in wrapper
    result = func(*args)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 101, in get_callable
    not module_has_submodule(import_module(parentmod), submod)):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
ImportError: No module named meetnet
Not Found: /info/730
Internal Server Error: /
Traceback (most recent call last):
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/response.py", line 82, in rendered_content
    content = template.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 140, in render
    return self._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 123, in render
    return compiled_parent._render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 134, in _render
    return self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/templatetags/l10n.py", line 35, in render
    output = self.nodelist.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/base.py", line 840, in render
    bit = self.render_node(node, context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/debug.py", line 78, in render_node
    return node.render(context)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 447, in render
    six.reraise(*exc_info)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 433, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=context.current_app)
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 536, in reverse
    return iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs))
  File "/home/theo/acaciadata.com/django/local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 456, in _reverse_with_prefix
    (lookup_view_s, args, kwargs, len(patterns), patterns))
NoReverseMatch: Reverse for 'well-info' with arguments '('',)' and keyword arguments '{}' not found. 1 pattern(s) tried: ['net/info/(?P<pk>\\d+)/$']
Not Found: /net/info579
Not Found: /net/info579
Not Found: /net/info284
Not Found: /media/
Not Found: /media/
